"""Venue name canonicalisation.

Cricsheet records the same ground under several strings as detail gets added
over time ("Grace Road" vs "Grace Road, Leicester"; "Eden Gardens" vs
"Eden Gardens, Kolkata"). That fragments per-(venue, season) priors the same
way franchise rebrands fragment team priors.

Each variant is mapped to its most specific form so all of a ground's history
accrues to one key. Generated by detecting nested-suffix chains; ambiguous
stems shared by DISTINCT grounds (notably bare "County Ground", which covers
Bristol/Chelmsford/Derby/Hove/Worcester/Northampton) are deliberately NOT
merged — they stay as-is and fall back to default_par, which is safer than
merging six different grounds.
"""
from __future__ import annotations

_CANONICAL: dict[str, str] = {
    "Arun Jaitley Stadium": "Arun Jaitley Stadium, Delhi",
    "Aurora Stadium": "Aurora Stadium, Launceston",
    "Bellerive Oval": "Bellerive Oval, Hobart",
    "Brabourne Stadium": "Brabourne Stadium, Mumbai",
    "Brian Lara Stadium, Tarouba": "Brian Lara Stadium, Tarouba, Trinidad",
    "Brisbane Cricket Ground": "Brisbane Cricket Ground, Woolloongabba, Brisbane",
    "Brisbane Cricket Ground, Woolloongabba": "Brisbane Cricket Ground, Woolloongabba, Brisbane",
    "College Ground": "College Ground, Cheltenham",
    "County Ground, New Road": "County Ground, New Road, Worcester",
    "Daren Sammy National Cricket Stadium, Gros Islet": "Daren Sammy National Cricket Stadium, Gros Islet, St Lucia",
    "Docklands Stadium": "Docklands Stadium, Melbourne",
    "Dr DY Patil Sports Academy": "Dr DY Patil Sports Academy, Mumbai",
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam",
    "Eden Gardens": "Eden Gardens, Kolkata",
    "Edgbaston": "Edgbaston, Birmingham",
    "Gaddafi Stadium": "Gaddafi Stadium, Lahore",
    "Grace Road": "Grace Road, Leicester",
    "Headingley": "Headingley, Leeds",
    "Himachal Pradesh Cricket Association Stadium": "Himachal Pradesh Cricket Association Stadium, Dharamsala",
    "International Sports Stadium": "International Sports Stadium, Coffs Harbour",
    "Kennington Oval": "Kennington Oval, London",
    "Kensington Oval, Bridgetown": "Kensington Oval, Bridgetown, Barbados",
    "Lord's": "Lord's, London",
    "M Chinnaswamy Stadium": "M Chinnaswamy Stadium, Bengaluru",
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium, Bengaluru",
    "MA Chidambaram Stadium": "MA Chidambaram Stadium, Chepauk, Chennai",
    "MA Chidambaram Stadium, Chepauk": "MA Chidambaram Stadium, Chepauk, Chennai",
    "Maharashtra Cricket Association Stadium": "Maharashtra Cricket Association Stadium, Pune",
    "Manuka Oval": "Manuka Oval, Canberra",
    "Merchant Taylors' School Ground": "Merchant Taylors' School Ground, Northwood",
    "National Stadium": "National Stadium, Karachi",
    "Old Trafford": "Old Trafford, Manchester",
    "Providence Stadium": "Providence Stadium, Guyana",
    "Punjab Cricket Association IS Bindra Stadium": "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh",
    "Punjab Cricket Association IS Bindra Stadium, Mohali": "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh",
    "Queen's Park": "Queen's Park, Chesterfield",
    "Queen's Park Oval, Port of Spain": "Queen's Park Oval, Port of Spain, Trinidad",
    "Radlett Cricket Club": "Radlett Cricket Club, Radlett",
    "Rajiv Gandhi International Stadium": "Rajiv Gandhi International Stadium, Uppal, Hyderabad",
    "Rajiv Gandhi International Stadium, Uppal": "Rajiv Gandhi International Stadium, Uppal, Hyderabad",
    "Riverside Ground": "Riverside Ground, Chester-le-Street",
    "Sawai Mansingh Stadium": "Sawai Mansingh Stadium, Jaipur",
    "Shaheed Veer Narayan Singh International Stadium": "Shaheed Veer Narayan Singh International Stadium, Raipur",
    "Sheikh Zayed Stadium": "Sheikh Zayed Stadium, Abu Dhabi",
    "Sir Vivian Richards Stadium, North Sound": "Sir Vivian Richards Stadium, North Sound, Antigua",
    "Sophia Gardens": "Sophia Gardens, Cardiff",
    "St Lawrence Ground": "St Lawrence Ground, Canterbury",
    "The Cooper Associates County Ground": "The Cooper Associates County Ground, Taunton",
    "The Rose Bowl": "The Rose Bowl, Southampton",
    "Trent Bridge": "Trent Bridge, Nottingham",
    "Wankhede Stadium": "Wankhede Stadium, Mumbai",
    "Warner Park, Basseterre": "Warner Park, Basseterre, St Kitts",
}


def canonical_venue(name: str | None) -> str:
    if not name:
        return ""
    return _CANONICAL.get(name, name)
